### PR TITLE
eslint

### PR DESCRIPTION
**Pull request by brettz9**
Hope you are ok with a little eslinting; I tried to keep most of your existing conventions, but I figured that the changes I made shouldn't be too disruptive (add strict mode closure, eqeqeq, jsdoc-expected removal of extra line break, but accepting currently invalidity, 80 char. length, simplify/consistent `this` naming by passing as arg. to forEach)

### CODE REVIEW

**Comment by alekseykulikov** [comment]
Cool! I have to use eslint in my open-source projects and your config is a good start. I don't agree with:
- strict 80 char. length - I would allow comments in the end
- jsdoc-expected removal of extra line break - I like the space between comment and code
- strict mode closure - let's just add "use strict" on top, because browserify wraps it to closure anyway

**Comment by alekseykulikov** [comment]
I  will improve .eslintrc by myself, thanks!

**Comment by brettz9** [comment]
Speaking of browserify (which I assume is working if browserify-test works?)--I guess you would expect that consuming repositories would do their own browserification, right?

**Comment by alekseykulikov** [comment]
Exactly. It can be consumed with browserify, webpack or other commonjs system.
I improved code style and added missing test for addCallback. Thanks for contribution!

I will release new version soon and I also want to try:
- setup browser testing with zuul
- pass tests in IE 9, 10, 11 using sauce-labs cloud testing
- (maybe) rewrite it with ES6+babel and improve eslint rules and jsdoc comments

**Pull request merged**
